apiVersion: dns3l.github.com/v1alpha1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: dns3l-certmgr-issuer
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-sample
spec:
  url: https://dns3l.example.com
  caid: letsencrypt
