name: Generate Yarn lockfile

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: corepack enable

      - name: Generate lockfile
        run: yarn install --no-immutable

      - name: Commit lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add yarn.lock

          if git diff --cached --quiet; then
            echo "Lockfile unchanged"
          else
            git commit -m "chore: generate yarn lockfile"
            git push
          fi
